#pragma once

#ifndef __FMSPROTOCOL_H__
#define __FMSPROTOCOL_H__

// --------- Command ---------------------
#define	CMD_GET_VERSION					0x05	//S

#define	CMD_RELAY_ON_OFF				0x12	//S
#define CMD_DIFF_FP_REGISTER			0x19	//v1.041	

#define	CMD_SET_SYSTEM_INFO				0x20	//S
#define	CMD_GET_SYSTEM_INFO				0x30	//S

#define	CMD_SET_EXT_USER_ID				0x31
#define	CMD_GET_EXT_USER_ID				0x32
#define CMD_GET_SENSOR_INFO				0x33

#define CMD_MAKE_RECORD_START			0x35	//S	
#define CMD_MAKE_RECORD_CONT			0x36	//S
#define CMD_MAKE_RECORD_END				0x37	//S			
#define CMD_GET_TEMPLATE				0x40	//S

#define	CMD_GET_IMAGE					0x43	//S
#define	CMD_GET_REC_COUNT				0x46	//S
#define	CMD_GET_MASTER_COUNT			0x47	//S

#define	CMD_FP_REGISTER_START			0x50  	//S
#define	CMD_FP_REGISTER_END				0x51	//S
#define	CMD_FP_CHANGE_START				0x52   	//S
#define	CMD_FP_CHANGE_END				0x53   	//S
#define	CMD_FP_DELETE					0x54	//S
#define	CMD_FP_VERIFY					0x55 	//S
#define	CMD_FP_IDENTIFY					0x56	//S
#define	CMD_FP_VERIFY_MASTER			0x57	//S
#define	CMD_FP_VERIFY_MASTER_END		0x58	//S
#define	CMD_FP_IDENTIFY_EX				0x59	// ryan JAN.09.2009
#define CMD_IS_REGISTERED_USER 			0x60	//S

#define CMD_DB_GET_RECCOUNT				0x70	//S
#define	CMD_DB_ADD_REC					0x71	//S
#define CMD_DB_DELETE_REC				0x72	//S
#define	CMD_DB_GET_REC					0x73	//S
#define	CMD_DB_GET_FIRSTREC				0x74	//S
#define	CMD_DB_GET_NEXTREC				0x75  	//S
#define	CMD_DB_DELETE_ALL				0x76  	//S
#define	CMD_DB_GET_CURRENTREC			0x77	//S
#define	CMD_DB_VERIFY					0x78	//S
#define	CMD_DB_IDENTIFY					0x79	//S
#define	CMD_DB_IDENTIFY_EX				0x7A	// ryan JAN.09.2009
#define	CMD_DB_VERIFY_MASTER			0x7B	//S
#define	CMD_DB_VERIFY_MASTER_END		0x7C	//S
#define	CMD_DB_GET_ID_LIST				0x7D	//S
#define	CMD_DB_GET_MASTER_LIST			0x7E	//S

#define	CMD_SET_USERDATA				0x92	// ryan jan.13.2009
#define	CMD_GET_USERDATA				0x93	// ryan jan.13.2009

#define	CMD_FP_AUTO_IDENTIFY_START		0xA1	//S
#define	CMD_FP_AUTO_IDENTIFY_STOP		0xA2	//S
#define	CMD_FP_AUTO_IDENTIFY			0xA3	//S
#define	CMD_INSTANT_VERIFY				0xD0	//S

#define	CMD_SET_IO_CONFIG				0xB0	// ryan jan.13.2009
#define	CMD_GET_IO_CONFIG				0xB1	// ryan jan.13.2009
#define	CMD_WRITE_IO					0xB2	// ryan jan.13.2009
#define	CMD_READ_IO						0xB3	// ryan jan.13.2009

//===================================
// UN20 specific commands, 0xE0 ~ EF			// 2/14/2017
#define CMD_SWITCH_ETHERNET_OVER_USB	0xE0
#define CMD_GET_FPA_INFO				0xE1

//==================================
// version control
#define CMD_GET_MODULE_VERSION			0xEA	// get version info file

//===================================
#define CMD_REQUEST_CONNECT     		0xF0	//S
#define CMD_GET_SERIAL	         		0xF6	//H
#define CMD_LOAD_MATCH_TEMPLATS			0xFA

//=============================
// for Bluetooth Power Off
#define CMD_SET_POWER_OFF_TIME			0xF7	//H

//-----------warning code--------------------------
#define WARNING_DB_LOADING				0x41
#define WARNING_DB_CHECKSUM				0x42

//-----------Error code ---------------------------
#define ERR_NONE                        0x00
#define ERR_FLASH_OPEN                  0x01	//?
#define ERR_SENSOR_OPEN                 0x02
#define ERR_REGISTER_FAILED             0x03
#define ERR_VERIFY_FAILED               0x04
#define ERR_ALREADY_REGISTERED_USER     0x05
#define ERR_USER_NOT_FOUND              0x06
#define ERR_TIMEOUT                     0x08
#define ERR_DB_FULL                     0x09
#define ERR_DB_WRONG_USERID             0x0A	//?
#define ERR_DB_NO_DATA                  0x0B
#define ERR_FUNCTION_FAIL               0x10
#define ERR_INSUFFICIENT_DATA           0x11
#define ERR_FLASH_WRITE_ERROR           0x12
#define ERR_FLASH_READ_ERROR            0x13
#define ERR_INVALID_PARAM               0x14
#define ERR_AUTHENTICATION_FAIL         0x17
#define ERR_IDENTIFY_FAILED             0x1B
#define ERR_CHECKSUM_ERROR              0x28    
#define ERR_INVALID_FPRECORD			0x30    

#define ERR_DB_MINEX_TO_SIMPLIFIED      0x32 // insert the DB generated by the MINEX algorithm into the simplified MINEX algorithm.
#define ERR_DB_SIMPLIFIED_TO_MINEX      0x33 // insert the DB generated by the simplified MINEX algorithm into the MINEX algorithm.
#define ERR_DB_SIMPLIFIED_TO_LMDB       0x34 // insert the DB generated by the simplified MINEX algorithm into the LMDB (MINEX algorithm).
#define ERR_REQUIRED_REBOOTING          0x35 // You have to reboot because you changed algorithm.

#define ERR_BREAK						0xFE
#define ERR_UNKNOWN_COMMAND             0xFF

#endif