
// SgBLEDemo.cpp: 
//

#include "stdafx.h"
#include "SgBLEDemo.h"
#include "SgBLEDemoDlg.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif


// CSgBLEDemoApp

BEGIN_MESSAGE_MAP(CSgBLEDemoApp, CWinApp)
	ON_COMMAND(ID_HELP, &CWinApp::OnHelp)
END_MESSAGE_MAP()


// CSgBLEDemoApp 

CSgBLEDemoApp::CSgBLEDemoApp()
{
}


CSgBLEDemoApp theApp;


// CSgBLEDemoApp 

BOOL CSgBLEDemoApp::InitInstance()
{
	// InitCommonControlsEx()
	INITCOMMONCONTROLSEX InitCtrls;
	InitCtrls.dwSize = sizeof(InitCtrls);
	InitCtrls.dwICC = ICC_WIN95_CLASSES;
	InitCommonControlsEx(&InitCtrls);

	CWinApp::InitInstance();

	CShellManager *pShellManager = new CShellManager;

	CMFCVisualManager::SetDefaultManager(RUNTIME_CLASS(CMFCVisualManagerWindows));

	SetRegistryKey(_T("Applications generated by the Local Application Wizard"));

	CSgBLEDemoDlg dlg;
	m_pMainWnd = &dlg;
	INT_PTR nResponse = dlg.DoModal();
	if (nResponse == IDOK)
	{
		// TODO: IDOK handler
	}
	else if (nResponse == IDCANCEL)
	{
		// TODO: IDCANCEL
	}
	else if (nResponse == -1)
	{
		TRACE(traceAppMsg, 0, "Warning: The application unexpectedly quits because the dialog could not be created.\n");
		TRACE(traceAppMsg, 0, "Warning: #define _AFX_NO_MFC_CONTROLS_IN_DIALOGS can not be performed when using MFC controls in a dialog box.\n");
	}

	if (pShellManager != nullptr)
	{
		delete pShellManager;
	}

#if !defined(_AFXDLL) && !defined(_AFX_NO_MFC_CONTROLS_IN_DIALOGS)
	ControlBarCleanUp();
#endif

	return FALSE;
}

